name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change version if necessary

      - name: Build (if needed)
        run: |
          # Add any build commands here, e.g., npm install, npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change this if your files are in a subdirectory
